name: json5_model
description: Gernerating Dart model class from Json files with one command.
version: 2.0.2
homepage: https://github.com/wilinz/json5_model
repository: https://github.com/wilinz/json5_model

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  args: ^2.4.2
  build: ^2.4.1
  glob: ^2.1.2
  logging: ^1.2.0
  io: ^1.0.4
  build_runner_core: ^7.2.10
  build_runner: ^2.4.6
  path: ^1.8.3
  json5: ^0.8.0
dev_dependencies:
  test: ^1.24.5
  lint: ^2.1.2
